name: Test and build
on:
  push:
    branches: [master]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: poetry install
      - name: Testing
        run: poetry run pytest
